---
title: "Cluster"
output: html_document
date: "2024-03-25"
---

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("iClusterPlus")
```

```{r setup, include=FALSE}
library(data.table)
library(iClusterPlus)
library(tidyverse)
library(lattice)
library(gplots)
```


```{r}
meth = fread("HumanMethylation450", sep= "\t")
meth <- as.data.frame(meth)
rownames(meth) = meth$`Composite Element REF`
```

```{r}
#bmi_data = read_csv("KIRC_BMI.csv") %>%
#  rename("name" = "TCGA Sample Code") %>%
#  filter(bmi != "underweight")
bmi_data = read_tsv("TCGA_&_Clinical_Data.tsv")
bmi_data = rename(bmi_data, "name" = "#Patient Identifier") %>% rename("bmiGroup" = "BMI Group") %>% filter(bmiGroup != "Underweight") %>% select(name, bmiGroup) %>% filter(!is.na(bmiGroup))
bmi_data <- mutate(bmi_data, bmiGroup = fct_recode(bmiGroup, "Normal" = "NW", "Obese" = "OB", "Overweight" = "OW"))
bmi_data$name <- gsub("-", ".", bmi_data$name)

```

```{r}
# Step 1: Remove columns that don't end in -01
meth <- meth[, grepl("-01$", colnames(meth))]

# Step 2: Remove parts of column names after the last "-"
colnames(meth) <- sub("(.*)-.*", "\\1", colnames(meth))

# Step 3: Replace all "-" with "."
colnames(meth) <- gsub("-", ".", colnames(meth))

# Extract the TCGA Sample Code column from bmi_data
sample_codes <- bmi_data$name

# Identify the common column names between 'meth' and 'sample_codes'
common_cols <- intersect(colnames(meth), sample_codes)

# Keep only the columns in 'meth' that are present in 'common_cols'
meth <- meth[, common_cols]
bmi_data = bmi_data %>%
  filter(name %in% common_cols)

```



```{r}
#Let's load in rna data
rna = read.csv("KIRC_mRNA_BMI.csv", sep=",")
common_cols = intersect(colnames(rna), common_cols)
rna <- rna[, common_cols]
rna <- rna[, colSums(is.na(rna)) == 0]
rna = as.data.frame(t(rna))
meth <- meth[, common_cols]
bmi_data = bmi_data %>%
  filter(name %in% common_cols)
```

```{r}
#Load in mirna data
mirna <- read_tsv("TCGA-KIRC.mirna.tsv")

# Step 1: Remove columns that don't end in -01A
mirna <- mirna[, grepl("-01A$", colnames(mirna))]

# Step 2: Remove parts of column names after the last "-"
colnames(mirna) <- sub("(.*)-.*", "\\1", colnames(mirna))

# Step 3: Replace all "-" with "."
colnames(mirna) <- gsub("-", ".", colnames(mirna))

mirna <- mirna[, colSums(is.na(mirna)) == 0]
mirna = as.data.frame(t(mirna))
mirna <- mirna[-c(1), ]
```
```{r}
meth = t(meth)
meth <- meth[, colSums(is.na(meth)) == 0]
meth <- as.data.frame(meth)
```

```{r}
common_rows = intersect(intersect(rownames(rna), rownames(meth)), rownames(mirna))
rna <- rna[common_rows,] %>% na.omit() %>% as.matrix()
meth <- meth[common_rows,] %>% na.omit() %>% as.matrix()
mirna <- mirna[common_rows,] %>% na.omit() %>% as.matrix()
``` 

```{r}
# Function to calculate Median Absolute Deviation (MAD)
mad <- function(x) {
  median(abs(x - median(x)))
}

# Select top 1881 features based on MAD for mRNA data
top_5000_mRNA <- names(sort(apply(rna, 2, mad), decreasing = TRUE)[0:1881])

# Select top 1881 features based on MAD for methylation data
top_5000_meth <- names(sort(apply(meth, 2, mad), decreasing = TRUE)[0:1881])

# Select top 1881 features based on MAD for miRNA data
#top_5000_mirna <- names(sort(apply(mirna, 2, mad), decreasing = TRUE)[0:1881])
```


```{r}
# Subset datasets with selected features
rna_selected <- rna[, top_5000_mRNA]
rna_selected <- log2(rna_selected + 1)
meth_selected <- meth[, top_5000_meth]
mirna_selected <- mirna
mirna_selected <- log2(mirna_selected + 1)
```
```{r}
#Make sure these are in the same order
meth_selected <- meth_selected[match(row.names(rna_selected), row.names(meth_selected)), ]
mirna_selected <- mirna[match(row.names(rna_selected), row.names(mirna_selected)), ]

rm(meth)
rm(mirna)
rm(rna)
```


```{r}
result <- iClusterBayes(meth_selected, rna_selected, mirna_selected,
	type = c("gaussian", "gaussian", "gaussian"),K=2,n.burnin=1000,n.draw=1200,
	prior.gamma=rep(0.1,6),sdev=0.5,beta.var.scale=1,thin=1,pp.cutoff=0.5)

```

```{r}
datasets = list(meth_selected, rna_selected, mirna_selected)
plotHMBayes(result, datasets, type = c("gaussian", "gaussian", "gaussian"), sample.order = NULL, row.order = NULL, sparse = c(TRUE, TRUE, TRUE), threshold = rep(0.5,length(datasets)), width = 5, col.scheme = rep(list(bluered(256)),length(datasets)), chr=NULL, plot.chr=NULL, cap=NULL)
```

```{r}
#bmi_data <- bmi_data[common_rows,]
clusters = result$clusters
bmi_data$Cluster = as.vector(clusters)


#Chisquare Test
tidy_data <- bmi_data %>% mutate(bmiGroup = factor(bmiGroup)) %>% 
  dplyr::count(Cluster, bmiGroup) %>%
  pivot_wider(names_from = Cluster, values_from = n, values_fill = 0)
chisq_result <- chisq.test(tidy_data[, -1])

p_value = chisq_result$p.value

# Count observations in each combination of cluster assignment and BMI category
count_data <- bmi_data %>%
  group_by(Cluster, bmiGroup) %>%
  summarise(Count = n()) %>%
  group_by(bmiGroup) %>%
  mutate(Percentage = (Count / sum(Count)) * 100)

count_data <- count_data %>% mutate(bmi = factor(bmiGroup)) #%>% mutate(bmi = fct_recode(bmiGroup, Normal = "normal", Overweight = "overweight",Obese= "obese"))

# Plot the data
p = ggplot(count_data, aes(x = bmiGroup, y = Percentage, fill = factor(Cluster))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "", y = "Percentage Per Cluster", fill = "Cluster Assignment") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 12),  # Adjust x-axis label size
        axis.text.y = element_text(size = 12))   # Adjust y-axis label size

my_colors <- c("#ADD8E6", "#6495ED", "#4169E1") 
p <- p + 
  annotate("text", x = Inf, y = Inf, label = paste("p-value:", round(p_value, 4)), 
           hjust = 1, vjust = 1, size = 4, color = "black", parse = TRUE) +
  scale_fill_manual(values = my_colors)

print(p)

ggsave("bayes_clusters.png", plot = p, width = 6, height = 4, dpi = 300)

```
