library(survival)
library(survminer)
library(tidyverse)
library(dplyr)
library(readr)
library(forestplot)

data = read_tsv("Input/TCGA_&_Clinical_Data.tsv")
# data = read_tsv("Downloads/TCGA_Clinical_Combined_With_BMI.tsv")

quartiles <- quantile(data$`Age at Diagnosis`, probs = c(0, 0.25, 0.5, 0.75, 1), na.rm = TRUE)

# mtData = read_csv("Downloads/Supplementary_file_1.csv") %>%
#   filter(Study=="KIRC") %>%
#   mutate(`#Patient Identifier` = paste0("TCGA-", `Sample ID`)) %>%
#   rename(`Mitochondria Log2 Fold Change` = `Log2 Fold Change`) %>%
#   select(`#Patient Identifier`, `Mitochondria Log2 Fold Change`)

# print(mtData)
# print(data$`PatientID`)
# data = full_join(data, mtData)
# mergedData = full_join(data, mtData)
#print(data$`Mitochondria Log2 Fold Change`)


#BMI Classification vs Tumor Size (Boxplot)
data$`BMI Classification` = factor(data$`BMI Classification`, 
                                   levels = c('Underweight', 'NW', 'OW', 'OB I', 'OB II', 'OB III'))
data$Sex = as.factor(toupper(data$Sex))
data$`Cancer Stage` = factor(toupper(data$`Cancer Stage`), levels = c("STAGE I", "STAGE II", "STAGE III", "STAGE IV"))
data = data %>% filter(!is.na(`BMI Classification`))
data = mutate(data, `Max Tumor Dimension` = as.numeric(`Max Tumor Dimension`)) %>%
  filter(`BMI Classification` != "Underweight") %>%
  rename(`PatientID` = `#Patient Identifier`) %>%
  mutate(`BMI Group` = case_when(`BMI Classification` %in% c("OB I", "OB II", "OB III") ~ "OB", TRUE ~ `BMI Classification`)) %>%
  mutate(`BMI Group` = factor(toupper(`BMI Group`), levels = c("NW", "OW", "OB"))) %>%
  filter(`Survival Since Diagnosis (Months)` != 0) %>%
  #mutate(`Age Quartile2` = ntile(`Age at Diagnosis`, 4)) %>%
  mutate(`Above or Below 60` = case_when(`Age at Diagnosis` >= 60 ~ "Above 60", `Age at Diagnosis` < 60 ~ "Below 60")) %>%
  mutate(`Above or Below 60` = factor(`Above or Below 60`, levels = c("Below 60", "Above 60"))) %>%
  mutate(`Cancer Stage Group` = case_when(
      `Cancer Stage` %in% c("STAGE I", "STAGE II") ~ "Stage I/II",
      `Cancer Stage` %in% c("STAGE III", "STAGE IV") ~ "Stage III/IV", TRUE ~ `Cancer Stage`)) %>%
  mutate(`Cancer Stage Group` = factor(`Cancer Stage Group`, levels = c("Stage I/II", "Stage III/IV"))) #%>%
  #write_tsv("Downloads/TCGA_Clinical_Combined_With_BMI.tsv")


nw_color <- "#56B4E9"  # Pastel Green
ow_color <- "#009E73"  # Pastel Blue
ob_colors <- c("#f7c8c9", "#D55E00", "#ff3a3a")  # Gradient of pastel reds

colorBlindFriendly = c("#009E73", "#56B4E9", "#D55E00")

# ggplot(data, aes(x = `BMI Group`, y = `Max Tumor Dimension`, fill = `BMI Group`)) +
#   geom_boxplot() +
#   labs(title = "Max Tumor Dimension by BMI Classification",
#        x = "BMI Classification",
#        y = "Max Tumor Dimension (units)") +
#   scale_fill_brewer(palette = "Pastel1") +
#   stat_summary(fun=mean, color ="#FDAE6B", shape = 23, fill ="#FDAE6B") +
#   theme_bw() +
#   scale_fill_manual(values = c(nw_color, ow_color, ob_colors[2]))

# ggplot(data, aes(x = `BMI Group`, y = `Mitochondria Log2 Fold Change`)) +
#   geom_boxplot() +
#   stat_summary(fun=mean, color ="#FDAE6B", shape = 23, fill ="#FDAE6B") +
#   theme_bw()

# ggplot(mergedData, aes(x = `BMI Group`, y = `Mitochondria Log2 Fold Change`)) +
#   geom_boxplot() +
#   stat_summary(fun=mean, color ="#FDAE6B", shape = 23, fill ="#FDAE6B") +
#   theme_bw()

#BMI Classification vs Tumor Size (Boxplot) with count numbers
data_counts <- data %>%
  group_by(`BMI Classification`) %>%
  summarise(Count = n())
data <- merge(data, data_counts, by = "BMI Classification", all.x = TRUE)
# ggplot(data, aes(x = `BMI Classification`, y = `Max Tumor Dimension`, fill= )) +
#   geom_boxplot() +
#   geom_text(aes(label = Count, y = -Inf), stat = "unique", 
#             position = position_dodge(width = 0.75), vjust = -0.5) +
#   labs(title = "Max Tumor Dimension by BMI Classification",
#        x = "BMI Classification",
#        y = "Max Tumor Dimension (units)") +
#   theme_bw() +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Count of BMI Classification Data
# ggplot(data, aes(x=`BMI Classification`)) +
#   geom_bar() +
#   geom_text(stat = 'count', aes(label = ..count.., y = ..count..), vjust = -0.5) +
#   theme_bw() +
#   labs(y = "Count")

counts_Classification <- boxplotData %>%
  group_by(`BMI Classification`, `Overall Survival Status Classification`) %>%
  summarise(count = n())

counts_Group <- boxplotData %>%
  group_by(`BMI Group`, `Overall Survival Status Classification`) %>%
  summarise(count = n())

#BoxPlot classes of obesity with survival status (Facet with living, deceased, and both, 5 boxpots)
# ggplot(data, aes(x = `BMI Classification`, y = `Survival Since Diagnosis (Months)`)) +
#   geom_boxplot() +
#   theme_bw() +
#   facet_wrap(~ `Overall Survival Status Classification`) + 
#   geom_text(data = counts_Classification, aes(label = count, y = -Inf), 
#             vjust = -0.5, hjust = 0.5, size = 3, position = position_nudge(x = 0)) +
#   ggtitle("ccRCC Survival Time by BMI Classification - Boxplot")

#Try with Colors
set.seed(123)
data2 <- data.frame(
  `BMI Classification` = rep(c("NW", "OW", "OB I", "OB II", "OB III"), each = 20),
  `Survival Since Diagnosis (Months)` = rnorm(100),
  `Overall Survival Status Classification` = rep(c("Living", "Deceased"), each = 50))

nw_color <- "#56B4E9"  # Pastel Green
ow_color <- "#009E73"  # Pastel Blue
ob_colors <- c("#f7c8c9", "#D55E00", "#ff3a3a")  # Gradient of pastel reds

colorBlindFriendly = c("#009E73", "#56B4E9", "#D55E00")

# Plotting
# ggplot(data, aes(x = `BMI Classification`, y = `Survival Since Diagnosis (Months)`, fill = `BMI Classification`)) +
#   geom_boxplot() +
#   theme_bw() +
#   facet_wrap(~ `Overall Survival Status Classification`) + 
#   geom_text(data = counts_Classification, aes(x = `BMI Classification`, label = count, y = -Inf), 
#             vjust = -0.5, hjust = 0.5, size = 3,
#             position = position_nudge(x = 0)) +
#   scale_fill_manual(values = c(NW = nw_color, OW = ow_color, 
#                                `OB I` = ob_colors[1], `OB II` = ob_colors[2], `OB III` = ob_colors[3]))
  #ggtitle("ccRCC Survival in Months by BMI Classification")

# ggplot(data, aes(x = `BMI Group`, y = `Survival Since Diagnosis (Months)`, fill = `BMI Group`)) +
#   geom_boxplot() +
#   theme_bw() +
#   facet_wrap(~ `Overall Survival Status Classification`) + 
#   geom_text(data = counts_Group, aes(x = `BMI Group`, label = count, y = -Inf), 
#             vjust = -0.5, hjust = 0.5, size = 3,
#             position = position_nudge(x = 0)) +
#   scale_fill_manual(values = c(NW = nw_color, OW = ow_color, `OB` = ob_colors[2])) +
#   ggtitle("ccRCC Survival in Months by BMI Classification")


#Kaplan meier (4 Kaplan meier NW to OW, OB1,2,3)
data <- data %>%
  rename(Months = `Survival Since Diagnosis (Months)`) %>%
  rename(Survival = `Overall Survival Status Number`) %>%
  rename(BMI_Class = `BMI Classification`) %>%
  rename(BMI_Group = `BMI Group`)

print(data$Months)

# fit <- survfit(Surv(Months, Survival) ~ BMI_Class, data = data)
# ggsurvplot(fit, data = data, pval = TRUE, conf.int = FALSE,
#            title = "ccRCC Survival by BMI Classification",
#            xlab = "Time (months)", ylab = "Survival probability",
#            legend.title = "BMI Classification:",
#            legend.labs = c("NW", "OW", "OB I", "OB II", "OB III"),
#            palette = c(nw_color, ow_color, ob_colors))


group_sizes <- data %>%
  group_by(BMI_Group) %>%
  summarise(Count = n())
totalObservations = sum(group_sizes$Count)
print(totalObservations)
group_labels <- setNames(group_sizes$Count, group_sizes$BMI_Group)

fit <- survfit(Surv(Months, Survival) ~ BMI_Group, data = data)
custom_legend_labs <- sapply(levels(data$BMI_Group), function(x) paste(x, " (", group_labels[x], ")", sep=""))

survPlot = ggsurvplot(fit, data = data, pval = TRUE, conf.int = FALSE,
           title = paste("ccRCC Survival by BMI Group (", totalObservations, ")", sep = ""),
           #title = NULL,
           break.time.by = 12,
           xlab = "Time (months)", ylab = "Survival probability",
           legend.title = "BMI Classification:",
           legend.labs = custom_legend_labs,
           risk.table = TRUE,
           risk.table.title = "Number at Risk",
           risk.table.col = "strata",
           tables.theme = theme_cleantable(),
           palette = c(nw_color, ow_color, ob_colors[2]))#c("black", "black", "black"))

survPlot$plot = survPlot$plot + theme(legend.title = element_text(size = 12))  # Adjust the size to your preference
print(survPlot)

cox_model = coxph(Surv(Months, Survival) ~ BMI_Group + `Above or Below 60` + Sex + `Cancer Stage Group`, data = data) # + `Tumor Grade`
summary(cox_model)

hazard_ratios <- exp(coef(cox_model))
conf_intervals <- exp(confint(cox_model))

# Create a data frame for forest plot
forest_data <- data.frame(
  variables = names(hazard_ratios),
  HR = hazard_ratios,
  lower = conf_intervals[, 1],
  upper = conf_intervals[, 2]
)

# Create the forest plot
# library(grid)
# forestplot(
#   title = "ccRCC Survival Cox Proportional Hazards Ratio",
#   mean = (forest_data$HR),
#   lower = (forest_data$lower),
#   upper = (forest_data$upper),
#   labeltext = (forest_data$variables),
#   #labeltext = c("OW BMI", "OB BMI", paste0("Age Q2: ", ageLevels[2]), paste0("Age Q3: ", ageLevels[3]), paste0("Age Q4: ", ageLevels[4]), "Male", "STAGE II", "STAGE III", "STAGE IV"),
#   is.summary=c(FALSE, rep(FALSE, nrow(forest_data)-1)),
#   clip=c(0.1, 6),  # set limits for the x-axis
#   xticks=c(0.1, 0.5, 1, 2, 3, 4, 5, 6),
#   refline = 1.0)
# #grid.lines(x = unit(c(0.5, 0.5), "npc"), y = unit(c(0, 1), "npc"), gp = gpar(col = "red"))
# 
# #print(data$`Age Quartile`)
# 
# forest_data_long <- tidyr::pivot_longer(forest_data, cols = c(HR, lower, upper), names_to = "Metric", values_to = "Value")

# Create the plot
# ggplot(data = forest_data, aes(x = variables, y = HR)) +
#   geom_point(size = 3) +  # This adds the dots for Hazard Ratios
#   geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +  # This adds the whiskers for confidence intervals
#   coord_flip() +  # Flips the coordinates to make the plot horizontal
#   theme_minimal() +
#   labs(title = "ccRCC Survival Cox Proportional Hazards Ratio",
#        x = "Variables", y = "Hazard Ratio") +
#   geom_hline(yintercept = 1, linetype = "solid", color = "grey35") +
#   scale_x_discrete(labels = rev(c("Male\n(Ref: Female)", "OW\n(Ref: NW)", "OB\n(Ref: NW)",
#                                   "Cancer Stages III/IV\n(Ref: Stages I/II)",
#                                   "Age Above 60\n(Ref: Age Below 60)")))
# print(forest_data)

data2 = filter(data, !is.na(`Tumor Grade`)) %>%
  mutate(`Tumor Grade` = factor(`Tumor Grade`, levels = c("G1", "G2", "G3", "G4"))) %>%
  mutate(`Tumor Grade Group` = case_when(
    `Tumor Grade` %in% c("G1", "G2") ~ "G1/G2", #Less Aggressive Cancers
    `Tumor Grade` %in% c("G3", "G4") ~ "G3/G4", TRUE ~ `Tumor Grade`)) %>% #More Aggressive Cancers
  mutate(`Tumor Grade Group` = factor(`Tumor Grade Group`, levels = c("G1/G2", "G3/G4")))


chi_square_result <- chisq.test(data2$BMI_Group, data2$`Tumor Grade Group`)
print(chi_square_result)
t_test_result <- t.test(BMI ~ `Tumor Grade Group`, data = data2)
print(t_test_result)
anova_result <- aov(BMI ~ `Tumor Grade Group`, data = data2)
print(summary(anova_result))


cox_model2 <- coxph(Surv(Months, Survival) ~ BMI_Group + `Above or Below 60` + Sex + `Cancer Stage Group` + `Tumor Grade Group`, data = data2)

# summary(cox_model2)

# hazard_ratios2 <- exp(coef(cox_model2))
# conf_intervals2 <- exp(confint(cox_model2))

# Create a data frame for forest plot
forest_data2 <- data.frame(
  variables = names(hazard_ratios2),
  HR = hazard_ratios2,
  lower = conf_intervals2[, 1],
  upper = conf_intervals2[, 2]
)

# p_values <- summary(cox_model2)$coefficients[, "Pr(>|z|)"]

significance_levels <- c("***", "**", "*")  # You can customize this based on your preference

forest_data2$significance <- ifelse(p_values < 0.001, significance_levels[1],
                                    ifelse(p_values < 0.01, significance_levels[2],
                                           ifelse(p_values < 0.05, significance_levels[3], "")))
forest_data2$pValue <- p_values

ggplot(data = forest_data2, aes(x = variables, y = HR, label = significance)) +
  geom_point(size = 3) +  # This adds the dots for Hazard Ratios
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +  # This adds the whiskers for confidence intervals
  coord_flip() +  # Flips the coordinates to make the plot horizontal
  theme_minimal() +
  geom_text(aes(label = significance), vjust = -0.5, color = "black", size = 4) +  # Adjust vjust to position text
  labs(x = "Variables", y = "Hazard Ratio") +
  geom_hline(yintercept = 1, linetype = "solid", color = "grey35") +
  scale_y_continuous(breaks = seq(floor(min(forest_data$HR)), ceiling(max(forest_data$upper)), by = 0.5)) +
  scale_x_discrete(labels = rev(c("Male\n(Ref: Female)", "OW\n(Ref: NW)", "OB\n(Ref: NW)",
                                  "Tumor Grades G3/G4\n(Ref: Grades G1/G2)", "Cancer Stages III/IV\n(Ref: Stages I/II)",
                                  "Age Above 60\n(Ref: Age Below 60)"))) + #, "Grade 2", "Grade 3", "Grade 4"
  annotate("text", x = 5.5, y = 3.55, label = "* = p < 0.05  \n*** = p < 0.001", hjust = 1, size = 3)

print(forest_data2)
